---
  :concurrency: 5
  staging:
    :concurrency: 10
  production:
    :concurrency: 20
  :queues:
    - default
    - messages_distribution
    - mailers
    - facebook_messages
    - twitter_messages
    - google_messages
